name: Rust

on:
  push:
    branches:
      - main

  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --all-targets
      - name: Test Suite
        run: cargo test
      - name: Documentation
        run: cargo doc
