[package]
name = "orbital-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
notify = "*"
wasmer = "*"
wgpu = "*"
winit = "*"

[dependencies.tokio]
version = "*"
features = ["full"]
