[workspace]

[package]
name = "orbital-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
futures = "*"
notify = "*"
wasmer = "*"
wgpu = "0.14.2"
winit = "*"

[dependencies.tokio]
version = "*"
features = ["full"]
