exclude_globs = [
    # This is rather simple code that runs as part of the CI build and regularly
    # during local development. This probably means that meaningful bugs in here
    # should become obvious pretty quickly, and writing automated tests for it
    # seems non-trivial.
    "dev/**",
]

# End-to-end tests are located in a dedicated crate. Without this option,
# `cargo mutants` will not run the tests from that dedicated crate against
# mutants in the main `monobloc` crate.
test_workspace = true
