[package]
name = "p2p-feed"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "*"
feed-rs = "*"
reqwest = "*"
serde = "*"
toml = "*"

[dependencies.tokio]
version = "*"
features = ["full"]
